services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - horariolabinf-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=horariolabinf
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - MONGO_URL=mongodb://mongo:27017/horariolabinf
    volumes:
      - ./backend:/app
      - /app/node_modules

    networks:
      - horariolabinf-network

  mobile:
    build:
      context: ./mobile
      dockerfile: Dockerfile
    ports:
      - "19006:19006"
      - "19001:19001"
      - "19002:19002"
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    volumes:
      - ./mobile:/app
      - /app/node_modules
    networks:
      - horariolabinf-network

networks:
  horariolabinf-network:
    external: true