

services:
  mongo:
    build:
      context: ./mongo
      dockerfile: Dockerfile
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/pmdb
    depends_on:
      - mongo
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
