FROM mongo:7.0

# Cria usuário mongodb (se não existir)
RUN id -u mongodb &>/dev/null || useradd -r -s /bin/false mongodb

# Copia os arquivos de configuração
COPY config /config
RUN chmod -R +rwx /config && cp /config/mongod.conf /etc/mongod.conf

# Cria diretório de dados do MongoDB
RUN if [ ! -d /data/db ]; then mkdir -p /data/db && chown -R mongodb:mongodb /data/db; fi

# Define o volume para persistência de dados (opcional)
VOLUME ["/data/db"]

# Expõe a porta padrão do MongoDB
EXPOSE 27017

# Comando de inicialização
CMD ["mongod","--config", "/etc/mongod.conf"]
